import { useEffect,useState } from 'react'
import { supabase } from '../../lib/supabase'
import { Card, Empty, PageHeader } from '../../components/Ui'
import type { KnowledgeBase,KnowledgeDocument,Organization,Profile } from '../../types/domain'

export function Knowledge({profile}:{profile:Profile}){const [orgs,setOrgs]=useState<Organization[]>([]);const [organizationId,setOrganizationId]=useState(profile.organization_id??'');const [bases,setBases]=useState<KnowledgeBase[]>([]);const [docs,setDocs]=useState<KnowledgeDocument[]>([]);const [kbName,setKbName]=useState('');const [kbCode,setKbCode]=useState('');const [selectedKb,setSelectedKb]=useState('');const [faqQ,setFaqQ]=useState('');const [faqA,setFaqA]=useState('');const [manualTitle,setManualTitle]=useState('');const [manualText,setManualText]=useState('');const [message,setMessage]=useState('')
 const load=async()=>{const [o,b,d]=await Promise.all([supabase.from('organizations').select('*'),supabase.from('knowledge_bases').select('*').order('created_at',{ascending:false}),supabase.from('knowledge_documents').select('*').order('created_at',{ascending:false})]);setOrgs((o.data??[]) as Organization[]);setBases((b.data??[]) as KnowledgeBase[]);setDocs((d.data??[]) as KnowledgeDocument[])};useEffect(()=>{void load()},[])
 const createKb=async(e:React.FormEvent)=>{e.preventDefault();const {data,error}=await supabase.from('knowledge_bases').insert({organization_id:organizationId,name:kbName,code:kbCode.toUpperCase().replace(/[^A-Z0-9_-]/g,'_')}).select('id').single();setMessage(error?.message??'تم إنشاء قاعدة المعرفة.');if(data){setKbName('');setKbCode('');setSelectedKb(data.id);await load()}}
 const addFaq=async(e:React.FormEvent)=>{e.preventDefault();const kb=bases.find(x=>x.id===selectedKb);if(!kb)return;const {error}=await supabase.from('knowledge_faq').insert({organization_id:kb.organization_id,knowledge_base_id:kb.id,question:faqQ,answer:faqA,language:'ar'});setMessage(error?.message??'تمت إضافة FAQ.');if(!error){setFaqQ('');setFaqA('')}}
 const addManual=async(e:React.FormEvent)=>{e.preventDefault();const kb=bases.find(x=>x.id===selectedKb);if(!kb)return;const {error}=await supabase.from('knowledge_documents').insert({organization_id:kb.organization_id,knowledge_base_id:kb.id,title:manualTitle,source_type:'manual_text',language:'ar',processing_status:'pending',metadata:{manualText}});setMessage(error?.message??'تمت إضافة النص إلى قائمة المعالجة.');if(!error){setManualTitle('');setManualText('');await load()}}
 const upload=async(file:File)=>{const kb=bases.find(x=>x.id===selectedKb);if(!kb)return;const ext=file.name.split('.').pop()?.toLowerCase();if(!ext||!['pdf','docx','txt'].includes(ext)){setMessage('المسموح PDF / DOCX / TXT فقط.');return}if(file.size>20*1024*1024){setMessage('الحد الأقصى 20MB.');return}const id=crypto.randomUUID();const path=`${kb.organization_id}/${kb.id}/${id}/${file.name.replace(/[^\p{L}\p{N}._-]/gu,'_')}`;const {error:storageError}=await supabase.storage.from('knowledge').upload(path,file,{upsert:false});if(storageError){setMessage(storageError.message);return}const {error}=await supabase.from('knowledge_documents').insert({id,organization_id:kb.organization_id,knowledge_base_id:kb.id,title:file.name,source_type:'file',original_file_name:file.name,storage_path:path,language:'ar',processing_status:'pending'});if(error){setMessage(error.message);return}setMessage('تم الرفع ووضع المستند في قائمة المعالجة.');await load()}
 const visibleBases=organizationId?bases.filter(b=>b.organization_id===organizationId):bases;const visibleDocs=selectedKb?docs.filter(d=>d.knowledge_base_id===selectedKb):docs
 return <><PageHeader title="المعرفة" description="Knowledge Bases، مستندات، FAQ ونصوص يدوية."/><Card><div className="grid-form">{profile.role==='SUPER_ADMIN'&&<select value={organizationId} onChange={e=>{setOrganizationId(e.target.value);setSelectedKb('')}}><option value="">اختر الجهة</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name_ar}</option>)}</select>}<select value={selectedKb} onChange={e=>setSelectedKb(e.target.value)}><option value="">اختر Knowledge Base</option>{visibleBases.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div>{message&&<p>{message}</p>}</Card><div className="two-col"><Card><h2>إنشاء Knowledge Base</h2><form className="stack" onSubmit={createKb}><input required placeholder="الاسم" value={kbName} onChange={e=>setKbName(e.target.value)}/><input required placeholder="CODE" value={kbCode} onChange={e=>setKbCode(e.target.value)}/><button disabled={!organizationId}>إنشاء</button></form></Card><Card><h2>إضافة مصدر</h2><div className="stack"><input type="file" accept=".pdf,.docx,.txt" disabled={!selectedKb} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/><form className="stack" onSubmit={addManual}><input required placeholder="عنوان النص اليدوي" value={manualTitle} onChange={e=>setManualTitle(e.target.value)}/><textarea required rows={4} value={manualText} onChange={e=>setManualText(e.target.value)} placeholder="النص"/><button disabled={!selectedKb}>إضافة Manual Text</button></form></div></Card></div><Card><h2>FAQ</h2><form className="grid-form" onSubmit={addFaq}><input required placeholder="السؤال" value={faqQ} onChange={e=>setFaqQ(e.target.value)}/><input required placeholder="الإجابة" value={faqA} onChange={e=>setFaqA(e.target.value)}/><button disabled={!selectedKb}>إضافة</button></form></Card><Card><h2>المستندات</h2>{visibleDocs.length===0?<Empty>لا توجد مستندات.</Empty>:<table><thead><tr><th>العنوان</th><th>النوع</th><th>الحالة</th><th>المعالجة</th></tr></thead><tbody>{visibleDocs.map(d=><tr key={d.id}><td>{d.title}</td><td>{d.source_type}</td><td>{d.is_active?'نشط':'متوقف'}</td><td>{d.processing_status}{d.processing_error&&<small className="error-text"> — {d.processing_error}</small>}</td></tr>)}</tbody></table>}</Card></>}
