import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { supabase } from '../../lib/supabase'
import { Badge, Card, Empty, FieldHint, Modal, PageHeader, PanelHeader } from '../../components/Ui'
import type { KnowledgeBase, KnowledgeDocument, Organization, Profile } from '../../types/domain'
import { useI18n, type AppLanguage } from '../../lib/i18n'

interface FaqRow{id:string;organization_id:string;knowledge_base_id:string;question:string;answer:string;language:string;priority:number;is_active:boolean}
type EditTarget={kind:'base';row:KnowledgeBase}|{kind:'document';row:KnowledgeDocument}|{kind:'faq';row:FaqRow}|null

export function Knowledge({profile}:{profile:Profile}){
  const {language,tr,valueLabel}=useI18n()
  const [orgs,setOrgs]=useState<Organization[]>([])
  const [organizationId,setOrganizationId]=useState(profile.organization_id??'')
  const [bases,setBases]=useState<KnowledgeBase[]>([])
  const [docs,setDocs]=useState<KnowledgeDocument[]>([])
  const [faqs,setFaqs]=useState<FaqRow[]>([])
  const [selectedKb,setSelectedKb]=useState('')
  const [contentLanguage,setContentLanguage]=useState<AppLanguage>(language)
  const [message,setMessage]=useState('')
  const [busy,setBusy]=useState(false)
  const [createKbOpen,setCreateKbOpen]=useState(false)
  const [kbName,setKbName]=useState('');const [kbCode,setKbCode]=useState('');const [kbDescription,setKbDescription]=useState('')
  const [faqQ,setFaqQ]=useState('');const [faqA,setFaqA]=useState('')
  const [manualTitle,setManualTitle]=useState('');const [manualText,setManualText]=useState('')
  const [urlTitle,setUrlTitle]=useState('');const [sourceUrl,setSourceUrl]=useState('')
  const [editTarget,setEditTarget]=useState<EditTarget>(null)
  const [editName,setEditName]=useState('');const [editDescription,setEditDescription]=useState('');const [editLanguage,setEditLanguage]=useState<AppLanguage>('ar');const [editAnswer,setEditAnswer]=useState('')

  const load=async()=>{const [o,b,d,f]=await Promise.all([supabase.from('organizations').select('*').order('name_ar'),supabase.from('knowledge_bases').select('*').order('created_at',{ascending:false}),supabase.from('knowledge_documents').select('*').order('created_at',{ascending:false}),supabase.from('knowledge_faq').select('*').order('priority',{ascending:false}).order('created_at',{ascending:false})]);setOrgs((o.data??[]) as Organization[]);setBases((b.data??[]) as KnowledgeBase[]);setDocs((d.data??[]) as KnowledgeDocument[]);setFaqs((f.data??[]) as FaqRow[])}
  useEffect(()=>{void load()},[])
  const visibleBases=useMemo(()=>organizationId?bases.filter(r=>r.organization_id===organizationId):bases,[bases,organizationId])
  const visibleDocs=useMemo(()=>selectedKb?docs.filter(r=>r.knowledge_base_id===selectedKb):[],[docs,selectedKb])
  const visibleFaqs=useMemo(()=>selectedKb?faqs.filter(r=>r.knowledge_base_id===selectedKb):[],[faqs,selectedKb])
  const selectedBase=bases.find(r=>r.id===selectedKb)??null

  const createKb=async(e:FormEvent)=>{e.preventDefault();if(!organizationId)return;setBusy(true);const {data,error}=await supabase.from('knowledge_bases').insert({organization_id:organizationId,name:kbName.trim(),code:kbCode.toUpperCase().replace(/[^A-Z0-9_-]/g,'_'),description:kbDescription.trim()||null}).select('id').single();setBusy(false);setMessage(error?.message??tr('تم إنشاء قاعدة المعرفة.','Knowledge base created.'));if(data){setKbName('');setKbCode('');setKbDescription('');setSelectedKb(data.id);setCreateKbOpen(false);await load()}}
  const addFaq=async(e:FormEvent)=>{e.preventDefault();if(!selectedBase)return;setBusy(true);const {error}=await supabase.from('knowledge_faq').insert({organization_id:selectedBase.organization_id,knowledge_base_id:selectedBase.id,question:faqQ.trim(),answer:faqA.trim(),language:contentLanguage});setBusy(false);setMessage(error?.message??tr('تمت إضافة السؤال الشائع.','FAQ added.'));if(!error){setFaqQ('');setFaqA('');await load()}}
  const addManual=async(e:FormEvent)=>{e.preventDefault();if(!selectedBase)return;setBusy(true);const {error}=await supabase.from('knowledge_documents').insert({organization_id:selectedBase.organization_id,knowledge_base_id:selectedBase.id,title:manualTitle.trim(),source_type:'manual_text',language:contentLanguage,processing_status:'pending',metadata:{manualText}});setBusy(false);setMessage(error?.message??tr('تمت إضافة النص إلى قائمة المعالجة.','Manual text queued for processing.'));if(!error){setManualTitle('');setManualText('');await load()}}
  const addUrl=async(e:FormEvent)=>{e.preventDefault();if(!selectedBase)return;let parsed:URL;try{parsed=new URL(sourceUrl.trim())}catch{setMessage(tr('أدخل رابطًا صحيحًا.','Enter a valid URL.'));return}if(!['http:','https:'].includes(parsed.protocol)){setMessage(tr('يُسمح بروابط HTTP وHTTPS فقط.','Only HTTP and HTTPS URLs are allowed.'));return}setBusy(true);const {error}=await supabase.from('knowledge_documents').insert({organization_id:selectedBase.organization_id,knowledge_base_id:selectedBase.id,title:urlTitle.trim()||parsed.hostname,source_type:'url',source_url:parsed.toString(),language:contentLanguage,processing_status:'pending',metadata:{}});setBusy(false);setMessage(error?.message??tr('تمت إضافة الرابط إلى قائمة المعالجة.','URL queued for processing.'));if(!error){setUrlTitle('');setSourceUrl('');await load()}}
  const upload=async(file:File)=>{if(!selectedBase)return;const ext=file.name.split('.').pop()?.toLowerCase();if(!ext||!['pdf','docx','txt'].includes(ext)){setMessage(tr('المسموح PDF / DOCX / TXT فقط.','Only PDF / DOCX / TXT files are allowed.'));return}if(file.size>20*1024*1024){setMessage(tr('الحد الأقصى 20MB.','Maximum file size is 20MB.'));return}setBusy(true);setMessage('');const id=crypto.randomUUID();const path=`${selectedBase.organization_id}/${selectedBase.id}/${id}/source.${ext}`;const {error:storageError}=await supabase.storage.from('knowledge').upload(path,file,{upsert:false,contentType:file.type||undefined});if(storageError){setBusy(false);setMessage(storageError.message);return}const {error}=await supabase.from('knowledge_documents').insert({id,organization_id:selectedBase.organization_id,knowledge_base_id:selectedBase.id,title:file.name,source_type:'file',original_file_name:file.name,storage_path:path,language:contentLanguage,processing_status:'pending'});if(error){await supabase.storage.from('knowledge').remove([path]);setBusy(false);setMessage(error.message);return}setBusy(false);setMessage(tr('تم الرفع ووضع المستند في قائمة المعالجة.','File uploaded and queued for processing.'));await load()}

  const openEdit=(target:Exclude<EditTarget,null>)=>{setEditTarget(target);if(target.kind==='base'){setEditName(target.row.name);setEditDescription(target.row.description??'');setEditLanguage('ar');setEditAnswer('')}else if(target.kind==='document'){setEditName(target.row.title);setEditDescription('');setEditLanguage(target.row.language==='en'?'en':'ar');setEditAnswer('')}else{setEditName(target.row.question);setEditAnswer(target.row.answer);setEditLanguage(target.row.language==='en'?'en':'ar');setEditDescription('')}}
  const saveEdit=async(e:FormEvent)=>{e.preventDefault();if(!editTarget)return;setBusy(true);let error:{message:string}|null=null;if(editTarget.kind==='base'){({error}=await supabase.from('knowledge_bases').update({name:editName.trim(),description:editDescription.trim()||null}).eq('id',editTarget.row.id))}else if(editTarget.kind==='document'){({error}=await supabase.from('knowledge_documents').update({title:editName.trim(),language:editLanguage}).eq('id',editTarget.row.id))}else{({error}=await supabase.from('knowledge_faq').update({question:editName.trim(),answer:editAnswer.trim(),language:editLanguage}).eq('id',editTarget.row.id))}setBusy(false);setMessage(error?.message??tr('تم حفظ التعديلات.','Changes saved.'));if(!error){setEditTarget(null);await load()}}
  const toggleBase=async(r:KnowledgeBase)=>{const {error}=await supabase.from('knowledge_bases').update({is_active:!r.is_active}).eq('id',r.id);setMessage(error?.message??tr(r.is_active?'تم تعطيل قاعدة المعرفة.':'تم تفعيل قاعدة المعرفة.',r.is_active?'Knowledge base disabled.':'Knowledge base enabled.'));if(!error)await load()}
  const deleteBase=async(r:KnowledgeBase)=>{if(!confirm(tr('سيتم حذف قاعدة المعرفة وكل المستندات والأسئلة التابعة لها. هل تريد المتابعة؟','This deletes the knowledge base and all of its documents and FAQs. Continue?')))return;const paths=docs.filter(d=>d.knowledge_base_id===r.id&&d.storage_path).map(d=>d.storage_path as string);const {error}=await supabase.from('knowledge_bases').delete().eq('id',r.id);if(error){setMessage(error.message);return}if(paths.length){const storage=await supabase.storage.from('knowledge').remove(paths);if(storage.error)setMessage(tr('تم حذف قاعدة المعرفة، لكن تعذر تنظيف بعض ملفات التخزين.','Knowledge base deleted, but some storage objects could not be cleaned up.'))}if(!paths.length)setMessage(tr('تم حذف قاعدة المعرفة.','Knowledge base deleted.'));if(selectedKb===r.id)setSelectedKb('');await load()}
  const toggleDocument=async(r:KnowledgeDocument)=>{const {error}=await supabase.from('knowledge_documents').update({is_active:!r.is_active}).eq('id',r.id);setMessage(error?.message??tr(r.is_active?'تم تعطيل المصدر.':'تم تفعيل المصدر.',r.is_active?'Source disabled.':'Source enabled.'));if(!error)await load()}
  const deleteDocument=async(r:KnowledgeDocument)=>{if(!confirm(tr('حذف هذا المصدر نهائيًا؟','Delete this source permanently?')))return;const {error}=await supabase.from('knowledge_documents').delete().eq('id',r.id);if(error){setMessage(error.message);return}if(r.storage_path){const storage=await supabase.storage.from('knowledge').remove([r.storage_path]);setMessage(storage.error?tr('تم حذف المصدر، لكن تعذر تنظيف ملف التخزين.','Source deleted, but its storage object could not be cleaned up.'):tr('تم حذف المصدر.','Source deleted.'))}else setMessage(tr('تم حذف المصدر.','Source deleted.'));await load()}
  const toggleFaq=async(r:FaqRow)=>{const {error}=await supabase.from('knowledge_faq').update({is_active:!r.is_active}).eq('id',r.id);setMessage(error?.message??tr(r.is_active?'تم تعطيل السؤال الشائع.':'تم تفعيل السؤال الشائع.',r.is_active?'FAQ disabled.':'FAQ enabled.'));if(!error)await load()}
  const deleteFaq=async(r:FaqRow)=>{if(!confirm(tr('حذف هذا السؤال الشائع؟','Delete this FAQ?')))return;const {error}=await supabase.from('knowledge_faq').delete().eq('id',r.id);setMessage(error?.message??tr('تم حذف السؤال الشائع.','FAQ deleted.'));if(!error)await load()}

  return <div className="screen screen-knowledge">
    <PageHeader title={tr('المعرفة','Knowledge')} description={tr('نظّم مصادر المعرفة وعدّلها أو عطّلها أو احذفها مع الحفاظ على عزل بيانات كل جهة.','Organize, edit, disable, or remove knowledge sources while preserving tenant isolation.')} actions={<button type="button" onClick={()=>setCreateKbOpen(true)}>{tr('إنشاء قاعدة معرفة','Create knowledge base')}</button>}/>
    <Card className="context-panel"><PanelHeader title={tr('سياق العمل','Working context')} description={tr('اختر الجهة وقاعدة المعرفة ولغة المحتوى قبل إضافة أو إدارة المصادر.','Choose the organization, knowledge base, and content language before adding or managing sources.')} meta={<span className="panel-index">01</span>}/><div className="grid-form context-grid">{profile.role==='SUPER_ADMIN'&&<label>{tr('الجهة','Organization')}<select value={organizationId} onChange={e=>{setOrganizationId(e.target.value);setSelectedKb('')}}><option value="">{tr('اختر الجهة','Select organization')}</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name_ar} / {o.name_en}</option>)}</select></label>}<label>{tr('قاعدة المعرفة','Knowledge base')}<select value={selectedKb} onChange={e=>setSelectedKb(e.target.value)}><option value="">{tr('اختر قاعدة المعرفة','Select knowledge base')}</option>{visibleBases.map(b=><option key={b.id} value={b.id}>{b.name}{b.is_active?'':` — ${tr('متوقفة','Inactive')}`}</option>)}</select></label><label>{tr('لغة المحتوى','Content language')}<select value={contentLanguage} onChange={e=>setContentLanguage(e.target.value as AppLanguage)}><option value="ar">{tr('العربية','Arabic')}</option><option value="en">{tr('الإنجليزية','English')}</option></select></label></div>{selectedBase&&<div className="management-toolbar"><div><strong>{selectedBase.name}</strong> <Badge tone={selectedBase.is_active?'good':'bad'}>{selectedBase.is_active?tr('نشطة','Active'):tr('متوقفة','Inactive')}</Badge></div><div className="actions"><button type="button" className="small ghost" onClick={()=>openEdit({kind:'base',row:selectedBase})}>{tr('تعديل','Edit')}</button><button type="button" className={`small ${selectedBase.is_active?'warning-action':'success-action'}`} onClick={()=>void toggleBase(selectedBase)}>{selectedBase.is_active?tr('تعطيل','Disable'):tr('تفعيل','Enable')}</button><button type="button" className="small danger-action" onClick={()=>void deleteBase(selectedBase)}>{tr('حذف','Delete')}</button></div></div>}{message&&<div className="inline-feedback" role="status">{message}</div>}</Card>

    <Card className="source-panel"><PanelHeader title={tr('إضافة مصدر معرفة','Add knowledge source')} description={tr('الملفات تحفظ باسم تقني آمن، بينما يبقى اسم الملف الأصلي كما رفعه المستخدم للعرض والتتبع.','Files use a safe technical storage key while preserving the original filename for display and tracking.')} meta={<Badge tone={busy?'warn':'neutral'}>{busy?tr('جارٍ التنفيذ','Working'):tr('جاهز','Ready')}</Badge>}/><div className="source-methods"><section className="source-method"><div className="source-method-head"><span className="source-method-index">A</span><div><h3>{tr('رفع ملف','Upload file')}</h3><p>{tr('PDF / DOCX / TXT حتى 20MB.','PDF / DOCX / TXT up to 20MB.')}</p></div></div><label>{tr('اختر ملفًا','Choose a file')}<input type="file" accept=".pdf,.docx,.txt" disabled={!selectedKb||busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></label></section><section className="source-method"><div className="source-method-head"><span className="source-method-index">B</span><div><h3>{tr('صفحة ويب','Web page')}</h3><p>{tr('لصفحة عامة واحدة.','For one public page.')}</p></div></div><form className="source-inline-form" onSubmit={addUrl}><label>{tr('العنوان','Title')}<input value={urlTitle} onChange={e=>setUrlTitle(e.target.value)} placeholder={tr('اختياري','Optional')}/></label><label className="source-url-field">{tr('الرابط','URL')}<input required type="url" dir="ltr" value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="https://example.com/page"/><FieldHint>{tr('العناوين المحلية والخاصة محظورة أثناء المعالجة.','Local and private addresses are blocked during processing.')}</FieldHint></label><button disabled={!selectedKb||busy}>{tr('إضافة','Add')}</button></form></section><section className="source-method"><div className="source-method-head"><span className="source-method-index">C</span><div><h3>{tr('نص يدوي','Manual text')}</h3><p>{tr('للسياسات أو المعلومات القصيرة.','For short policies or information.')}</p></div></div><form className="source-inline-form" onSubmit={addManual}><label>{tr('العنوان','Title')}<input required value={manualTitle} onChange={e=>setManualTitle(e.target.value)}/></label><label className="source-text-field">{tr('المحتوى','Content')}<textarea required rows={4} value={manualText} onChange={e=>setManualText(e.target.value)}/></label><button disabled={!selectedKb||busy}>{tr('إضافة','Add')}</button></form></section></div></Card>

    <Card className="faq-panel"><PanelHeader title={tr('الأسئلة الشائعة','FAQ')} description={tr('إجابات معتمدة يمكن تعديلها أو تعطيلها أو حذفها.','Approved answers that can be edited, disabled, or deleted.')} meta={<Badge>{visibleFaqs.length}</Badge>}/><form className="grid-form faq-form" onSubmit={addFaq}><label>{tr('السؤال','Question')}<input required value={faqQ} onChange={e=>setFaqQ(e.target.value)}/></label><label>{tr('الإجابة المعتمدة','Approved answer')}<input required value={faqA} onChange={e=>setFaqA(e.target.value)}/></label><div className="form-submit-row"><button disabled={!selectedKb||busy}>{tr('إضافة سؤال شائع','Add FAQ')}</button></div></form>{visibleFaqs.length>0&&<div className="entity-list">{visibleFaqs.map(r=><div key={r.id} className={`entity-card ${r.is_active?'':'soft-disabled'}`}><div className="entity-card-main"><strong>{r.question}</strong><small>{r.answer}</small></div><div className="row-actions"><button type="button" className="small ghost" onClick={()=>openEdit({kind:'faq',row:r})}>{tr('تعديل','Edit')}</button><button type="button" className={`small ${r.is_active?'warning-action':'success-action'}`} onClick={()=>void toggleFaq(r)}>{r.is_active?tr('تعطيل','Disable'):tr('تفعيل','Enable')}</button><button type="button" className="small danger-action" onClick={()=>void deleteFaq(r)}>{tr('حذف','Delete')}</button></div></div>)}</div>}</Card>

    <Card className="table-card documents-panel"><PanelHeader title={tr('المستندات والمصادر','Documents and sources')} description={tr('تعديل الاسم واللغة أو تعطيل المصدر أو حذفه نهائيًا.','Edit title/language, disable a source, or permanently delete it.')} meta={<Badge>{visibleDocs.length}</Badge>}/>{visibleDocs.length===0?<Empty>{tr('اختر قاعدة معرفة تحتوي على مصادر.','Select a knowledge base with sources.')}</Empty>:<table className="data-table"><thead><tr><th>{tr('العنوان','Title')}</th><th>{tr('النوع','Type')}</th><th>{tr('اللغة','Language')}</th><th>{tr('الحالة','Status')}</th><th>{tr('المعالجة','Processing')}</th><th className="actions-cell">{tr('الإجراءات','Actions')}</th></tr></thead><tbody>{visibleDocs.map(r=><tr key={r.id} className={r.is_active?'':'soft-disabled'}><td className="cell-primary"><div>{r.title}</div>{r.source_url&&<small><a href={r.source_url} target="_blank" rel="noreferrer" dir="ltr">{r.source_url}</a></small>}</td><td>{valueLabel(r.source_type)}</td><td>{valueLabel(r.language)}</td><td><Badge tone={r.is_active?'good':'bad'}>{r.is_active?tr('نشط','Active'):tr('متوقف','Inactive')}</Badge></td><td><Badge tone={r.processing_status==='ready'?'good':r.processing_status==='failed'?'bad':'warn'}>{valueLabel(r.processing_status)}</Badge></td><td className="actions-cell"><div className="row-actions"><button type="button" className="small ghost" onClick={()=>openEdit({kind:'document',row:r})}>{tr('تعديل','Edit')}</button><button type="button" className={`small ${r.is_active?'warning-action':'success-action'}`} onClick={()=>void toggleDocument(r)}>{r.is_active?tr('تعطيل','Disable'):tr('تفعيل','Enable')}</button><button type="button" className="small danger-action" onClick={()=>void deleteDocument(r)}>{tr('حذف','Delete')}</button></div></td></tr>)}</tbody></table>}</Card>

    <Modal open={createKbOpen} onClose={()=>setCreateKbOpen(false)} title={tr('إنشاء قاعدة معرفة','Create knowledge base')} description={tr('يتم إنشاء قاعدة المعرفة من نافذة مستقلة لتبقى شاشة المصادر مرتبة.','Knowledge bases are created in a focused dialog to keep the source workspace clean.')}><form className="modal-stack" onSubmit={createKb}><label>{tr('اسم قاعدة المعرفة','Knowledge base name')}<input required value={kbName} onChange={e=>setKbName(e.target.value)} placeholder={tr('مثال: القبول والتسجيل','Example: Admissions')}/></label><label>{tr('الكود','Code')}<input required dir="ltr" value={kbCode} onChange={e=>setKbCode(e.target.value)} placeholder="ADMISSIONS"/></label><label>{tr('الوصف','Description')}<textarea rows={3} value={kbDescription} onChange={e=>setKbDescription(e.target.value)}/></label><div className="form-actions"><button disabled={!organizationId||busy}>{tr('إنشاء','Create')}</button><button type="button" className="ghost" onClick={()=>setCreateKbOpen(false)}>{tr('إلغاء','Cancel')}</button></div></form></Modal>
    <Modal open={Boolean(editTarget)} onClose={()=>setEditTarget(null)} title={tr('تعديل البيانات','Edit data')}><form className="modal-stack" onSubmit={saveEdit}><label>{editTarget?.kind==='faq'?tr('السؤال','Question'):tr('الاسم أو العنوان','Name or title')}<input required value={editName} onChange={e=>setEditName(e.target.value)}/></label>{editTarget?.kind==='base'&&<label>{tr('الوصف','Description')}<textarea rows={3} value={editDescription} onChange={e=>setEditDescription(e.target.value)}/></label>}{editTarget?.kind==='faq'&&<label>{tr('الإجابة','Answer')}<textarea required rows={4} value={editAnswer} onChange={e=>setEditAnswer(e.target.value)}/></label>}{(editTarget?.kind==='document'||editTarget?.kind==='faq')&&<label>{tr('اللغة','Language')}<select value={editLanguage} onChange={e=>setEditLanguage(e.target.value as AppLanguage)}><option value="ar">{tr('العربية','Arabic')}</option><option value="en">{tr('الإنجليزية','English')}</option></select></label>}<div className="form-actions"><button disabled={busy}>{tr('حفظ التعديلات','Save changes')}</button><button type="button" className="ghost" onClick={()=>setEditTarget(null)}>{tr('إلغاء','Cancel')}</button></div></form></Modal>
  </div>
}
