import type { SupabaseClient } from 'npm:@supabase/supabase-js@2.112.3'

export type VoiceProvider = 'gemini' | 'openai' | 'groq'
export type VoiceRetentionMode = 'audio_and_transcript' | 'transcript_only'
export type VoiceReplyMode = 'text_only' | 'voice_for_voice' | 'always_voice'
export interface VoiceSettings {
  voice_enabled: boolean
  voice_provider: VoiceProvider
  voice_model: string
  voice_retention_mode: VoiceRetentionMode
  voice_reply_mode: VoiceReplyMode
  voice_tts_provider: 'gemini'
  voice_tts_model: string
  voice_tts_voice: string
  max_voice_seconds: number
  included_monthly_voice_minutes: number | null
  included_monthly_tts_minutes: number | null
  monthly_ai_cost_limit_usd: number | null
}
export interface VoiceTranscript { text:string;provider:VoiceProvider;model:string;inputTokens:number;outputTokens:number;estimatedCost:number;latencyMs:number }

const MAX_AUDIO_BYTES=8*1024*1024
const mimeAliases:Record<string,string>={'audio/x-wav':'audio/wav','audio/mp3':'audio/mpeg'}
const allowedMimes=new Set(['audio/webm','audio/ogg','audio/wav','audio/mpeg','audio/aac','audio/flac','audio/mp4'])
const extensionByMime:Record<string,string>={'audio/webm':'webm','audio/ogg':'ogg','audio/wav':'wav','audio/mpeg':'mp3','audio/aac':'aac','audio/flac':'flac','audio/mp4':'m4a'}
const monthStart=()=>new Date(Date.UTC(new Date().getUTCFullYear(),new Date().getUTCMonth(),1)).toISOString()
const cleanModel=(value:string)=>value.trim().replace(/^models\//,'').slice(0,180)
const normalizeMime=(value:string)=>{const base=value.toLowerCase().split(';',1)[0]?.trim()??'';return mimeAliases[base]??base}

function base64(bytes:Uint8Array){let binary='';const chunkSize=0x8000;for(let offset=0;offset<bytes.length;offset+=chunkSize){const chunk=bytes.subarray(offset,Math.min(offset+chunkSize,bytes.length));binary+=String.fromCharCode(...chunk)}return btoa(binary)}
async function providerSecret(admin:SupabaseClient,provider:string){const setting=await admin.from('ai_provider_settings').select('id').is('organization_id',null).eq('provider',provider).eq('is_active',true).order('is_default',{ascending:false}).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(setting.error)throw setting.error;if(!setting.data)throw new Error(`voice_provider_not_configured:${provider}`);const secret=await admin.rpc('get_ai_provider_secret',{p_provider_setting_id:setting.data.id});if(secret.error)throw secret.error;if(typeof secret.data!=='string'||!secret.data.trim())throw new Error(`voice_provider_secret_missing:${provider}`);return secret.data.trim()}
async function estimateCost(admin:SupabaseClient,provider:string,model:string,inputTokens:number,outputTokens:number,durationMs:number){const price=await admin.from('model_pricing').select('input_cost_per_million,output_cost_per_million,audio_cost_per_minute').eq('provider',provider).eq('model',model).eq('is_active',true).lte('effective_from',new Date().toISOString().slice(0,10)).order('effective_from',{ascending:false}).limit(1).maybeSingle();if(price.error)throw price.error;const audioPerMinute=Number(price.data?.audio_cost_per_minute??0);if(audioPerMinute>0)return durationMs/60000*audioPerMinute;return inputTokens/1_000_000*Number(price.data?.input_cost_per_million??0)+outputTokens/1_000_000*Number(price.data?.output_cost_per_million??0)}

async function transcribeGemini(secret:string,model:string,bytes:Uint8Array,mimeType:string,language:'ar'|'en'|null){const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(cleanModel(model))}:generateContent`,{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':secret},body:JSON.stringify({contents:[{role:'user',parts:[{text:`Transcribe this customer voice message accurately. Return transcript text only, with no commentary or markdown. Preserve names, numbers, URLs, and proper nouns. Language hint: ${language??'auto'}.`},{inlineData:{mimeType:normalizeMime(mimeType),data:base64(bytes)}}]}],generationConfig:{temperature:0,maxOutputTokens:2048}}),signal:AbortSignal.timeout(45000)});const payload=await response.json() as {candidates?:Array<{content?:{parts?:Array<{text?:string}>}}>;usageMetadata?:{promptTokenCount?:number;candidatesTokenCount?:number};error?:{message?:string}};if(!response.ok)throw new Error(`voice_transcription_failed:${payload.error?.message??response.status}`);const text=payload.candidates?.[0]?.content?.parts?.map(part=>part.text??'').join('').trim()??'';if(!text)throw new Error('voice_transcription_empty');return{text,inputTokens:Number(payload.usageMetadata?.promptTokenCount??0),outputTokens:Number(payload.usageMetadata?.candidatesTokenCount??0)}}
async function transcribeOpenAiCompatible(secret:string,provider:'openai'|'groq',model:string,bytes:Uint8Array,mimeType:string,language:'ar'|'en'|null){const form=new FormData();const normalizedMime=normalizeMime(mimeType);form.set('file',new Blob([bytes],{type:normalizedMime}),`voice.${extensionByMime[normalizedMime]??'bin'}`);form.set('model',cleanModel(model));form.set('response_format','json');if(language)form.set('language',language);const endpoint=provider==='groq'?'https://api.groq.com/openai/v1/audio/transcriptions':'https://api.openai.com/v1/audio/transcriptions';const response=await fetch(endpoint,{method:'POST',headers:{authorization:`Bearer ${secret}`},body:form,signal:AbortSignal.timeout(45000)});const payload=await response.json() as {text?:string;error?:{message?:string};usage?:{input_tokens?:number;output_tokens?:number}};if(!response.ok)throw new Error(`voice_transcription_failed:${payload.error?.message??response.status}`);const text=payload.text?.trim()??'';if(!text)throw new Error('voice_transcription_empty');return{text,inputTokens:Number(payload.usage?.input_tokens??0),outputTokens:Number(payload.usage?.output_tokens??0)}}

export function assertAudioFile(file:File){const mimeType=normalizeMime(file.type);if(!allowedMimes.has(mimeType))throw new Error('unsupported_audio_type');if(file.size<=0||file.size>MAX_AUDIO_BYTES)throw new Error('audio_file_too_large');return{mimeType,extension:extensionByMime[mimeType]??'bin'}}
export async function resolveVoiceSettings(admin:SupabaseClient,organizationId:string):Promise<VoiceSettings>{
 const result=await admin.from('organization_agents').select('voice_enabled,voice_provider,voice_model,voice_retention_mode,voice_reply_mode,voice_tts_provider,voice_tts_model,voice_tts_voice,max_voice_seconds,included_monthly_voice_minutes,included_monthly_tts_minutes,monthly_ai_cost_limit_usd').eq('organization_id',organizationId).maybeSingle();if(result.error)throw result.error
 if(!result.data)return{voice_enabled:false,voice_provider:'gemini',voice_model:'gemini-3.5-flash-lite',voice_retention_mode:'audio_and_transcript',voice_reply_mode:'text_only',voice_tts_provider:'gemini',voice_tts_model:'gemini-3.1-flash-tts-preview',voice_tts_voice:'Sulafat',max_voice_seconds:120,included_monthly_voice_minutes:null,included_monthly_tts_minutes:null,monthly_ai_cost_limit_usd:null}
 const voiceRetentionMode:VoiceRetentionMode=result.data.voice_retention_mode==='transcript_only'?'transcript_only':'audio_and_transcript'
 const replyMode:VoiceReplyMode=result.data.voice_reply_mode==='always_voice'?'always_voice':result.data.voice_reply_mode==='voice_for_voice'?'voice_for_voice':'text_only'
 return{voice_enabled:Boolean(result.data.voice_enabled),voice_provider:result.data.voice_provider as VoiceProvider,voice_model:cleanModel(result.data.voice_model),voice_retention_mode:voiceRetentionMode,voice_reply_mode:replyMode,voice_tts_provider:'gemini',voice_tts_model:cleanModel(result.data.voice_tts_model??'gemini-3.1-flash-tts-preview'),voice_tts_voice:String(result.data.voice_tts_voice??'Sulafat').trim().slice(0,80)||'Sulafat',max_voice_seconds:Number(result.data.max_voice_seconds??120),included_monthly_voice_minutes:result.data.included_monthly_voice_minutes==null?null:Number(result.data.included_monthly_voice_minutes),included_monthly_tts_minutes:result.data.included_monthly_tts_minutes==null?null:Number(result.data.included_monthly_tts_minutes),monthly_ai_cost_limit_usd:result.data.monthly_ai_cost_limit_usd==null?null:Number(result.data.monthly_ai_cost_limit_usd)}
}
export async function assertVoiceQuota(admin:SupabaseClient,organizationId:string,settings:VoiceSettings,durationMs:number){if(!settings.voice_enabled)throw new Error('voice_not_enabled');if(!Number.isFinite(durationMs)||durationMs<=0)throw new Error('voice_duration_required');if(durationMs>settings.max_voice_seconds*1000)throw new Error('voice_duration_exceeded');const start=monthStart();const [orgSettings,messages,attachments,costRows]=await Promise.all([admin.from('organization_settings').select('monthly_message_limit').eq('organization_id',organizationId).maybeSingle(),admin.from('messages').select('id',{count:'exact',head:true}).eq('organization_id',organizationId).eq('role','user').gte('created_at',start),settings.included_monthly_voice_minutes==null?Promise.resolve({data:[],error:null}):admin.from('message_attachments').select('duration_ms').eq('organization_id',organizationId).eq('audio_source','customer_voice').gte('created_at',start),settings.monthly_ai_cost_limit_usd==null?Promise.resolve({data:[],error:null}):admin.from('usage_logs').select('estimated_cost').eq('organization_id',organizationId).gte('created_at',start)]);if(orgSettings.error)throw orgSettings.error;if(messages.error)throw messages.error;if(attachments.error)throw attachments.error;if(costRows.error)throw costRows.error;const messageLimit=orgSettings.data?.monthly_message_limit==null?null:Number(orgSettings.data.monthly_message_limit);if(messageLimit!=null&&(messages.count??0)>=messageLimit)throw new Error('message_monthly_limit_exceeded');if(settings.included_monthly_voice_minutes!=null){const usedMs=(attachments.data??[]).reduce((sum,row)=>sum+Number(row.duration_ms??0),0);if(usedMs+durationMs>settings.included_monthly_voice_minutes*60000)throw new Error('voice_monthly_limit_exceeded')}if(settings.monthly_ai_cost_limit_usd!=null){const cost=(costRows.data??[]).reduce((sum,row)=>sum+Number(row.estimated_cost??0),0);if(cost>=settings.monthly_ai_cost_limit_usd)throw new Error('ai_cost_limit_exceeded')}}
export async function transcribeAudio(admin:SupabaseClient,settings:VoiceSettings,file:File,durationMs:number,language:'ar'|'en'|null):Promise<VoiceTranscript>{const{mimeType}=assertAudioFile(file),bytes=new Uint8Array(await file.arrayBuffer()),secret=await providerSecret(admin,settings.voice_provider),started=performance.now();const result=settings.voice_provider==='gemini'?await transcribeGemini(secret,settings.voice_model,bytes,mimeType,language):await transcribeOpenAiCompatible(secret,settings.voice_provider,settings.voice_model,bytes,mimeType,language);const estimatedCost=await estimateCost(admin,settings.voice_provider,settings.voice_model,result.inputTokens,result.outputTokens,durationMs);return{text:result.text,provider:settings.voice_provider,model:settings.voice_model,inputTokens:result.inputTokens,outputTokens:result.outputTokens,estimatedCost,latencyMs:Math.round(performance.now()-started)}}
