import { useEffect,useState } from 'react'
import { supabase } from '../../lib/supabase'
import { adminApi } from '../../lib/adminApi'
import { Card, Empty, PageHeader } from '../../components/Ui'
import type { ApiClient,Organization,Profile } from '../../types/domain'
export function ApiClients({profile}:{profile:Profile}){const [rows,setRows]=useState<ApiClient[]>([]);const [orgs,setOrgs]=useState<Organization[]>([]);const [organizationId,setOrganizationId]=useState(profile.organization_id??'');const [name,setName]=useState('');const [code,setCode]=useState('');const [shownKey,setShownKey]=useState('');const [error,setError]=useState('')
 const load=async()=>{const [c,o]=await Promise.all([supabase.from('api_clients_safe').select('*').order('created_at',{ascending:false}),supabase.from('organizations').select('*')]);setRows((c.data??[]) as ApiClient[]);setOrgs((o.data??[]) as Organization[])};useEffect(()=>{void load()},[])
 const create=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{const r=await adminApi<{apiKey:string}>({action:'create_api_client',organizationId,name,code,capabilities:['chat'],rateLimitPerMinute:60});setShownKey(r.apiKey);setName('');setCode('');await load()}catch(err){setError(err instanceof Error?err.message:'تعذر الإنشاء')}}
 const rotate=async(id:string)=>{if(!confirm('سيتم إلغاء المفتاح السابق فورًا. متابعة؟'))return;const r=await adminApi<{apiKey:string}>({action:'rotate_api_key',apiClientId:id});setShownKey(r.apiKey);await load()}
 return <><PageHeader title="API Clients" description="مفاتيح Server-to-Server تظهر مرة واحدة ولا تُخزن بصورتها الأصلية."/><Card><form className="grid-form" onSubmit={create}>{profile.role==='SUPER_ADMIN'&&<select required value={organizationId} onChange={e=>setOrganizationId(e.target.value)}><option value="">اختر الجهة</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name_ar}</option>)}</select>}<input required placeholder="Name" value={name} onChange={e=>setName(e.target.value)}/><input required placeholder="CODE" value={code} onChange={e=>setCode(e.target.value)}/><button>إنشاء API Client</button></form>{error&&<p className="error-text">{error}</p>}{shownKey&&<div className="secret-once"><strong>انسخ المفتاح الآن — لن يظهر مرة أخرى</strong><code>{shownKey}</code><button onClick={()=>void navigator.clipboard.writeText(shownKey)}>نسخ</button></div>}</Card><Card>{rows.length===0?<Empty>لا توجد API Clients.</Empty>:<table><thead><tr><th>الاسم</th><th>Code</th><th>Prefix</th><th>Rate limit</th><th>الحالة</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.code}</td><td><code>{r.api_key_prefix}</code></td><td>{r.rate_limit_per_minute}/min</td><td>{r.is_active?'نشط':'متوقف'}</td><td><button className="small" onClick={()=>void rotate(r.id)}>Rotate</button></td></tr>)}</tbody></table>}</Card></>}
