import { useEffect,useMemo,useState } from 'react'
import { Badge,Card,Empty,FieldHint,Modal,PageHeader,PanelHeader,Spinner } from '../../components/Ui'
import { adminApi } from '../../lib/adminApi'
import { useI18n } from '../../lib/i18n'
import { fetchProviderModelCatalog,type ProviderCatalogModel,type ProviderModelCatalog } from '../../lib/modelCatalog'
import { supabase } from '../../lib/supabase'
import type { Organization } from '../../types/domain'

type ProviderRow={id:string;provider:string;chat_model:string;embedding_model:string;is_default:boolean}
type Agent={
 organization_id:string;agent_name:string;plan_name:string;chat_provider:string;chat_model:string;embedding_provider:string;embedding_model:string;fallback_provider:string|null;fallback_model:string|null
 voice_enabled:boolean;voice_provider:'gemini'|'openai'|'groq';voice_model:string;max_voice_seconds:number;included_monthly_voice_minutes:number|null
 monthly_price:number;billing_currency:'SAR'|'USD'|'AED'|'EUR';included_monthly_messages:number|null;included_monthly_tokens:number|null;monthly_ai_cost_limit_usd:number|null;markup_percent:number;notes:string|null
 is_active:boolean;last_tested_at:string|null;last_test_status:'untested'|'passed'|'failed';last_test_latency_ms:number|null;last_test_error:string|null;updated_at:string
}
type Usage={organization_id:string;customer_messages:number;total_tokens:number;estimated_cost_usd:number;voice_duration_ms:number}
type AgentTestResult={chatLatencyMs:number;embeddingLatencyMs:number;fallbackLatencyMs:number|null;latencyMs:number}
type ModelKind='chat'|'embedding'

const providers=['gemini','openrouter','openai'] as const
const providerLabel=(value:string)=>value==='gemini'?'Gemini':value==='openrouter'?'OpenRouter':value==='openai'?'OpenAI':value==='groq'?'Groq':value
const nullableNumber=(value:string)=>value.trim()===''?null:Number(value)
const formatCompact=(value:number)=>new Intl.NumberFormat(undefined,{notation:value>=10000?'compact':'standard',maximumFractionDigits:1}).format(value)
const formatMinutes=(ms:number)=>`${(ms/60000).toFixed(ms>=600000?0:1)}m`
const runtimeSignature=(agent:Pick<Agent,'chat_provider'|'chat_model'|'embedding_provider'|'embedding_model'|'fallback_provider'|'fallback_model'>)=>JSON.stringify([agent.chat_provider,agent.chat_model.trim(),agent.embedding_provider,agent.embedding_model.trim(),agent.fallback_provider??'',agent.fallback_model?.trim()??''])

export function OrganizationAgents(){
 const {tr}=useI18n()
 const [orgs,setOrgs]=useState<Organization[]>([]),[agents,setAgents]=useState<Agent[]>([]),[usage,setUsage]=useState<Usage[]>([]),[providerRows,setProviderRows]=useState<ProviderRow[]>([])
 const [catalogs,setCatalogs]=useState<Record<string,ProviderModelCatalog>>({}),[catalogLoading,setCatalogLoading]=useState<Record<string,boolean>>({}),[catalogErrors,setCatalogErrors]=useState<Record<string,string>>({})
 const [editing,setEditing]=useState<Agent|null>(null),[initialRuntime,setInitialRuntime]=useState(''),[testedRuntime,setTestedRuntime]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState('')

 const load=async()=>{
  setLoading(true);setMessage('')
  const [orgResult,agentResult,usageResult,providerResult]=await Promise.all([
   supabase.from('organizations').select('*').order('name_ar'),supabase.from('organization_agents').select('*').order('updated_at',{ascending:false}),supabase.from('organization_agent_monthly_usage').select('*'),supabase.from('ai_provider_settings').select('id,provider,chat_model,embedding_model,is_default').is('organization_id',null).eq('is_active',true).order('provider')])
  const error=orgResult.error??agentResult.error??usageResult.error??providerResult.error;if(error)setMessage(error.message)
  setOrgs((orgResult.data??[]) as Organization[])
  setAgents((agentResult.data??[]).map(row=>({...row,voice_enabled:Boolean(row.voice_enabled),voice_provider:(row.voice_provider??'gemini') as Agent['voice_provider'],voice_model:row.voice_model??'gemini-3.5-flash-lite',max_voice_seconds:Number(row.max_voice_seconds??120),included_monthly_voice_minutes:row.included_monthly_voice_minutes==null?null:Number(row.included_monthly_voice_minutes),monthly_price:Number(row.monthly_price),monthly_ai_cost_limit_usd:row.monthly_ai_cost_limit_usd==null?null:Number(row.monthly_ai_cost_limit_usd),markup_percent:Number(row.markup_percent)})) as Agent[])
  setUsage((usageResult.data??[]).map(row=>({organization_id:row.organization_id,customer_messages:Number(row.customer_messages),total_tokens:Number(row.total_tokens),estimated_cost_usd:Number(row.estimated_cost_usd),voice_duration_ms:Number(row.voice_duration_ms??0)})) as Usage[])
  setProviderRows((providerResult.data??[]) as ProviderRow[]);setLoading(false)
 }
 useEffect(()=>{void load()},[])
 const orgById=useMemo(()=>new Map(orgs.map(org=>[org.id,org])),[orgs]),usageByOrg=useMemo(()=>new Map(usage.map(row=>[row.organization_id,row])),[usage])
 const availableProvider=(name:string)=>providerRows.find(row=>row.provider===name),activeAgents=agents.filter(agent=>agent.is_active).length,voiceAgents=agents.filter(agent=>agent.voice_enabled).length,monthCost=usage.reduce((sum,row)=>sum+row.estimated_cost_usd,0)

 const loadCatalog=async(provider:string,force=false)=>{if(!provider)return null;if(!force&&catalogs[provider])return catalogs[provider];if(catalogLoading[provider])return null;setCatalogLoading(v=>({...v,[provider]:true}));setCatalogErrors(v=>({...v,[provider]:''}));try{const catalog=await fetchProviderModelCatalog(provider);setCatalogs(v=>({...v,[provider]:catalog}));return catalog}catch(error){setCatalogErrors(v=>({...v,[provider]:error instanceof Error?error.message:'model_catalog_failed'}));return null}finally{setCatalogLoading(v=>({...v,[provider]:false}))}}
 const modelOptions=(provider:string,kind:ModelKind,currentModel:string|null|undefined)=>{const catalog=catalogs[provider],rows=[...(kind==='chat'?(catalog?.chatModels??[]):(catalog?.embeddingModels??[]))],configured=availableProvider(provider),defaultId=kind==='chat'?(catalog?.defaultChatModel??configured?.chat_model):(catalog?.defaultEmbeddingModel??configured?.embedding_model);for(const id of [currentModel?.trim(),defaultId?.trim()])if(id&&!rows.some(model=>model.id===id))rows.unshift({id,name:id,free:false,contextLength:null,structured:kind==='chat'});const seen=new Set<string>();return rows.filter(model=>model.id&&!seen.has(model.id)&&Boolean(seen.add(model.id)))}
 const modelOptionLabel=(model:ProviderCatalogModel)=>`${model.free?tr('مجاني · ','FREE · '):''}${model.name}${model.name!==model.id?` — ${model.id}`:''}`
 const catalogHint=(provider:string,kind:ModelKind)=>catalogLoading[provider]?tr('جارٍ تحميل قائمة النماذج من المزود…','Loading the provider model list…'):catalogErrors[provider]?tr('تعذر تحديث القائمة؛ يبقى النموذج المحفوظ متاحًا.','Could not refresh the catalog; the saved model remains available.'):catalogs[provider]?tr(`تم تحميل ${kind==='chat'?catalogs[provider].chatModels.length:catalogs[provider].embeddingModels.length} نموذجًا من ${providerLabel(provider)}.`,`${kind==='chat'?catalogs[provider].chatModels.length:catalogs[provider].embeddingModels.length} models loaded from ${providerLabel(provider)}.`):tr('تُحمّل النماذج تلقائيًا حسب المزود.','Models load automatically for the selected provider.')

 const openAgent=(agent:Agent)=>{const copy={...agent};setEditing(copy);setInitialRuntime(runtimeSignature(copy));setTestedRuntime(agent.last_test_status==='passed'?runtimeSignature(copy):'');setMessage('');const selected=[copy.chat_provider,copy.embedding_provider,copy.fallback_provider,copy.voice_provider==='gemini'?'gemini':null].filter((v):v is string=>Boolean(v));void Promise.all([...new Set(selected)].map(provider=>loadCatalog(provider)))}
 const patch=(values:Partial<Agent>)=>setEditing(current=>current?{...current,...values}:current)
 const applyProviderDefault=(role:'chat'|'embedding'|'fallback',provider:string)=>{const known=availableProvider(provider);if(role==='chat')patch({chat_provider:provider,chat_model:known?.chat_model??''});if(role==='embedding')patch({embedding_provider:provider,embedding_model:known?.embedding_model??''});if(role==='fallback')patch({fallback_provider:provider||null,fallback_model:provider?(known?.chat_model??''):null});if(provider)void loadCatalog(provider)}
 const testRuntime=async()=>{if(!editing)return;setBusy(true);setMessage('');try{const result=await adminApi<AgentTestResult>({action:'test_agent_runtime',organizationId:editing.organization_id,agent:{chatProvider:editing.chat_provider,chatModel:editing.chat_model,embeddingProvider:editing.embedding_provider,embeddingModel:editing.embedding_model,fallbackProvider:editing.fallback_provider,fallbackModel:editing.fallback_model}});setTestedRuntime(runtimeSignature(editing));patch({last_test_status:'passed',last_tested_at:new Date().toISOString(),last_test_latency_ms:result.latencyMs,last_test_error:null});setMessage(tr(`نجح اختبار الوكيل: المحادثة ${result.chatLatencyMs}ms، التضمين ${result.embeddingLatencyMs}ms${result.fallbackLatencyMs!=null?`، الاحتياط ${result.fallbackLatencyMs}ms`:''}.`,`Agent test passed: chat ${result.chatLatencyMs}ms, embeddings ${result.embeddingLatencyMs}ms${result.fallbackLatencyMs!=null?`, fallback ${result.fallbackLatencyMs}ms`:''}.`))}catch(error){patch({last_test_status:'failed',last_tested_at:new Date().toISOString(),last_test_error:error instanceof Error?error.message:'test_failed'});setTestedRuntime('');setMessage(error instanceof Error?error.message:tr('فشل اختبار الوكيل.','Agent test failed.'))}finally{setBusy(false)}}
 const save=async(event:React.FormEvent)=>{event.preventDefault();if(!editing)return;const signature=runtimeSignature(editing),runtimeChanged=signature!==initialRuntime;if(runtimeChanged&&signature!==testedRuntime){setMessage(tr('اختبر إعدادات النموذج الجديدة بنجاح قبل الحفظ.','Test the changed model configuration successfully before saving.'));return}if(!editing.agent_name.trim()||!editing.plan_name.trim()||!editing.chat_model.trim()||!editing.embedding_model.trim()||(editing.voice_enabled&&!editing.voice_model.trim()))return;setBusy(true);setMessage('');try{const payload={...editing,agent_name:editing.agent_name.trim(),plan_name:editing.plan_name.trim(),chat_model:editing.chat_model.trim(),embedding_model:editing.embedding_model.trim(),fallback_provider:editing.fallback_provider||null,fallback_model:editing.fallback_provider?editing.fallback_model?.trim()||null:null,voice_provider:editing.voice_enabled?editing.voice_provider:'gemini',voice_model:editing.voice_model.trim()||'gemini-3.5-flash-lite',notes:editing.notes?.trim()||null,last_test_status:runtimeChanged?'passed':editing.last_test_status,last_tested_at:runtimeChanged?new Date().toISOString():editing.last_tested_at,last_test_error:runtimeChanged?null:editing.last_test_error};const result=await supabase.from('organization_agents').upsert(payload,{onConflict:'organization_id'});if(result.error)throw result.error;setEditing(null);setMessage(tr('تم حفظ الوكيل والباقة وإعدادات الصوت.','Agent, plan, and voice settings saved.'));await load()}catch(error){setMessage(error instanceof Error?error.message:tr('تعذر حفظ الوكيل.','Unable to save the agent.'))}finally{setBusy(false)}}
 if(loading)return <div className="agent-center"><Spinner/></div>

 return <div className="screen agent-plans-screen">
  <PageHeader title={tr('وكلاء الجهات والباقات','Organization Agents & Plans')} description={tr('خصص نماذج المحادثة والمعرفة والصوت والحدود والسعر لكل جهة من نقطة تحكم واحدة.','Assign chat, knowledge, voice, limits, and commercial pricing per organization from one control plane.')} actions={<button type="button" className="ghost" onClick={()=>void load()}>{tr('تحديث البيانات','Refresh')}</button>}/>
  <div className="agent-metric-grid"><Card className="agent-metric"><span>{tr('الجهات','Organizations')}</span><strong>{orgs.length}</strong><small>{tr('لكل جهة وكيل مستقل','Each organization has an isolated runtime')}</small></Card><Card className="agent-metric"><span>{tr('الوكلاء النشطون','Active agents')}</span><strong>{activeAgents}</strong><small>{tr('يمكن إيقاف الوكيل دون حذف الإعدادات','Agents can be paused without deleting settings')}</small></Card><Card className="agent-metric"><span>{tr('الصوت مفعّل','Voice enabled')}</span><strong>{voiceAgents}</strong><small>{tr('جهات تقبل رسائل صوتية','Organizations accepting voice messages')}</small></Card><Card className="agent-metric"><span>{tr('تكلفة AI هذا الشهر','AI cost this month')}</span><strong>${monthCost.toFixed(2)}</strong><small>{tr('تشمل التفريغ الصوتي عند وجود تسعير','Includes transcription when pricing is configured')}</small></Card></div>
  <Card className="agent-board"><PanelHeader title={tr('خريطة تشغيل الجهات','Organization runtime map')} description={tr('المسار الظاهر هو ما يستخدمه العميل فعليًا، والصوت يتحول إلى نص ثم يدخل نفس RAG.','This is the real customer runtime; voice is transcribed then enters the same RAG flow.')} meta={<Badge>{agents.length}</Badge>}/>{agents.length===0?<Empty>{tr('لا توجد إعدادات وكلاء بعد.','No organization agents are configured yet.')}</Empty>:<div className="agent-list">{agents.map(agent=>{const org=orgById.get(agent.organization_id),month=usageByOrg.get(agent.organization_id),messageRatio=agent.included_monthly_messages?Math.min(100,((month?.customer_messages??0)/agent.included_monthly_messages)*100):0;return <article className={`agent-row${agent.is_active?'':' paused'}`} key={agent.organization_id}>
   <div className="agent-org-block"><div className="agent-status-line"><span className={`agent-live-dot${agent.is_active?'':' off'}`}/><span>{agent.is_active?tr('نشط','Active'):tr('متوقف','Paused')}</span></div><h3>{org?.name_ar??agent.agent_name}</h3><p>{org?.name_en??org?.code??'—'}</p><span className="agent-name-tag">{agent.agent_name}</span></div>
   <div className="agent-route" aria-label={tr('مسار الوكيل','Agent routing path')}><div className="route-node primary"><span>{tr('محادثة','Chat')}</span><strong>{providerLabel(agent.chat_provider)}</strong><small>{agent.chat_model}</small></div><span className="route-arrow">→</span><div className="route-node knowledge"><span>{tr('معرفة','Embedding')}</span><strong>{providerLabel(agent.embedding_provider)}</strong><small>{agent.embedding_model}</small></div><span className="route-arrow">→</span><div className={`route-node fallback${agent.fallback_provider?'':' muted'}`}><span>{tr('احتياط','Fallback')}</span><strong>{agent.fallback_provider?providerLabel(agent.fallback_provider):tr('غير مستخدم','Not used')}</strong><small>{agent.fallback_model??tr('المسار الأساسي فقط','Primary only')}</small></div></div>
   <div className="agent-commercial"><span className="plan-label">{agent.plan_name}</span><strong>{agent.monthly_price.toLocaleString()} <small>{agent.billing_currency}/{tr('شهر','mo')}</small></strong><div className="agent-usage-line"><span>{tr('رسائل الشهر','Messages')}</span><b>{formatCompact(month?.customer_messages??0)}{agent.included_monthly_messages?` / ${formatCompact(agent.included_monthly_messages)}`:''}</b></div>{agent.included_monthly_messages&&<div className="agent-progress"><span style={{width:`${messageRatio}%`}}/></div>}<div className="agent-usage-line"><span>{tr('الصوت','Voice')}</span><b>{agent.voice_enabled?`${formatMinutes(month?.voice_duration_ms??0)}${agent.included_monthly_voice_minutes?` / ${agent.included_monthly_voice_minutes}m`:''}`:tr('غير مفعّل','Off')}</b></div><div className="agent-cost-line"><span>{tr('تكلفة المزود','Provider cost')}</span><b>${(month?.estimated_cost_usd??0).toFixed(2)}</b></div></div>
   <div className="agent-row-actions"><Badge tone={agent.voice_enabled?'good':'neutral'}>{agent.voice_enabled?tr('صوت','Voice'):tr('نص','Text')}</Badge><Badge tone={agent.last_test_status==='passed'?'good':agent.last_test_status==='failed'?'bad':'warn'}>{agent.last_test_status==='passed'?tr('مختبر','Tested'):agent.last_test_status==='failed'?tr('فشل الاختبار','Test failed'):tr('غير مختبر','Untested')}</Badge><button type="button" onClick={()=>openAgent(agent)}>{tr('إدارة الوكيل','Manage agent')}</button></div>
  </article>})}</div>}</Card>
  {message&&!editing&&<div className="inline-feedback" role="status">{message}</div>}
  <Modal open={Boolean(editing)} onClose={()=>setEditing(null)} title={tr('إدارة الوكيل والباقة','Manage agent & plan')} description={editing?`${orgById.get(editing.organization_id)?.name_ar??''} · ${orgById.get(editing.organization_id)?.code??''}`:undefined}>
   {editing&&<form className="agent-editor" onSubmit={save}>
    <section className="agent-editor-section"><div className="agent-editor-heading"><span>01</span><div><h3>{tr('هوية الوكيل','Agent identity')}</h3><p>{tr('الاسم والحالة الخاصة بهذه الجهة.','Name and runtime status for this organization.')}</p></div></div><div className="agent-form-grid two"><label>{tr('اسم الوكيل','Agent name')}<input required value={editing.agent_name} onChange={e=>patch({agent_name:e.target.value})}/></label><label>{tr('حالة الوكيل','Agent status')}<select value={editing.is_active?'active':'paused'} onChange={e=>patch({is_active:e.target.value==='active'})}><option value="active">{tr('نشط','Active')}</option><option value="paused">{tr('متوقف','Paused')}</option></select></label></div></section>
    <section className="agent-editor-section runtime-section"><div className="agent-editor-heading"><span>02</span><div><h3>{tr('مسار الذكاء الاصطناعي','AI runtime route')}</h3><p>{tr('اختر نماذج المحادثة والمعرفة والاحتياط. تغيير التضمين يعيد فهرسة معرفة الجهة تلقائيًا.','Choose chat, embedding, and fallback models. Changing embeddings re-indexes this organization automatically.')}</p></div></div><div className="agent-runtime-grid">
     <div className="runtime-column"><strong>{tr('المحادثة الأساسية','Primary chat')}</strong><label>{tr('المزود','Provider')}<select value={editing.chat_provider} onChange={e=>applyProviderDefault('chat',e.target.value)}>{providers.map(value=><option key={value} value={value}>{providerLabel(value)}</option>)}</select></label><label>{tr('النموذج','Model')}<select required dir="ltr" value={editing.chat_model} onChange={e=>patch({chat_model:e.target.value})}><option value="" disabled>{tr('اختر نموذج المحادثة','Select chat model')}</option>{modelOptions(editing.chat_provider,'chat',editing.chat_model).map(model=><option key={model.id} value={model.id}>{modelOptionLabel(model)}</option>)}</select><FieldHint>{catalogHint(editing.chat_provider,'chat')}</FieldHint></label></div>
     <div className="runtime-column"><strong>{tr('قاعدة المعرفة','Knowledge embeddings')}</strong><label>{tr('المزود','Provider')}<select value={editing.embedding_provider} onChange={e=>applyProviderDefault('embedding',e.target.value)}>{providers.map(value=><option key={value} value={value}>{providerLabel(value)}</option>)}</select></label><label>{tr('نموذج التضمين','Embedding model')}<select required dir="ltr" value={editing.embedding_model} onChange={e=>patch({embedding_model:e.target.value})}><option value="" disabled>{tr('اختر نموذج التضمين','Select embedding model')}</option>{modelOptions(editing.embedding_provider,'embedding',editing.embedding_model).map(model=><option key={model.id} value={model.id}>{modelOptionLabel(model)}</option>)}</select><FieldHint>{catalogHint(editing.embedding_provider,'embedding')}</FieldHint></label></div>
     <div className="runtime-column"><strong>{tr('الاحتياط','Fallback')}</strong><label>{tr('المزود','Provider')}<select value={editing.fallback_provider??''} onChange={e=>applyProviderDefault('fallback',e.target.value)}><option value="">{tr('بدون احتياط','No fallback')}</option>{providers.map(value=><option key={value} value={value}>{providerLabel(value)}</option>)}</select></label><label>{tr('النموذج الاحتياطي','Fallback model')}<select dir="ltr" disabled={!editing.fallback_provider} value={editing.fallback_model??''} onChange={e=>patch({fallback_model:e.target.value})}><option value="">{editing.fallback_provider?tr('اختر النموذج الاحتياطي','Select fallback model'):tr('اختر مزودًا أولًا','Select a provider first')}</option>{editing.fallback_provider&&modelOptions(editing.fallback_provider,'chat',editing.fallback_model).map(model=><option key={model.id} value={model.id}>{modelOptionLabel(model)}</option>)}</select>{editing.fallback_provider&&<FieldHint>{catalogHint(editing.fallback_provider,'chat')}</FieldHint>}</label></div>
    </div><div className="agent-test-bar"><div><strong>{tr('اختبار عقد التشغيل الحقيقي','Test the real runtime contract')}</strong><small>{tr('يفحص Structured JSON + Embedding 1536 + Fallback قبل اعتماد تغيير النماذج.','Checks Structured JSON + 1536 embeddings + fallback before model changes are accepted.')}</small></div><button type="button" className="ghost" disabled={busy} onClick={()=>void testRuntime()}>{busy?tr('جارٍ الاختبار…','Testing…'):tr('اختبار الوكيل','Test agent')}</button></div></section>
    <section className="agent-editor-section voice-agent-section"><div className="agent-editor-heading"><span>03</span><div><h3>{tr('الرسائل الصوتية','Voice messages')}</h3><p>{tr('يُحفظ الصوت بشكل خاص، ثم يحوّله Gemini إلى نص ويمر النص في نفس قاعدة المعرفة. الرد يبقى نصيًا.','Audio is stored privately, Gemini transcribes it, and the transcript enters the same knowledge flow. Replies remain text.')}</p></div></div><div className="agent-form-grid three"><label>{tr('حالة الصوت','Voice status')}<select value={editing.voice_enabled?'enabled':'disabled'} onChange={e=>{const enabled=e.target.value==='enabled';patch({voice_enabled:enabled,voice_provider:'gemini'});if(enabled)void loadCatalog('gemini')}}><option value="disabled">{tr('غير مفعّل','Disabled')}</option><option value="enabled">{tr('مفعّل','Enabled')}</option></select></label><label>{tr('مزود التفريغ','Transcription provider')}<select value={editing.voice_provider} disabled={!editing.voice_enabled} onChange={e=>patch({voice_provider:e.target.value as Agent['voice_provider']})}><option value="gemini">Gemini</option></select><FieldHint>{tr('الإنتاج الحالي يستخدم Gemini Audio. البنية الخلفية جاهزة لإضافة مزودي تفريغ آخرين لاحقًا.','Production currently uses Gemini Audio. The backend is ready for additional transcription providers later.')}</FieldHint></label><label>{tr('نموذج الصوت','Voice model')}<select dir="ltr" disabled={!editing.voice_enabled} value={editing.voice_model} onChange={e=>patch({voice_model:e.target.value})}>{modelOptions('gemini','chat',editing.voice_model).map(model=><option key={model.id} value={model.id}>{modelOptionLabel(model)}</option>)}</select><FieldHint>{catalogHint('gemini','chat')}</FieldHint></label><label>{tr('الحد الأقصى للرسالة (ثانية)','Max message length (seconds)')}<input type="number" min="10" max="600" value={editing.max_voice_seconds} disabled={!editing.voice_enabled} onChange={e=>patch({max_voice_seconds:Math.max(10,Math.min(600,Number(e.target.value)||120))})}/></label><label>{tr('الدقائق الصوتية المشمولة شهريًا','Included voice minutes / month')}<input type="number" min="0" value={editing.included_monthly_voice_minutes??''} disabled={!editing.voice_enabled} onChange={e=>patch({included_monthly_voice_minutes:nullableNumber(e.target.value)})}/><FieldHint>{tr('اتركها فارغة لعدم وضع حد دقائق مستقل.','Leave blank for no separate voice-minute limit.')}</FieldHint></label><div className="voice-plan-summary"><small>{tr('استهلاك الشهر','This month')}</small><strong>{formatMinutes(usageByOrg.get(editing.organization_id)?.voice_duration_ms??0)}</strong><span>{tr('يُحتسب التفريغ ضمن تكلفة AI للجهة.','Transcription is included in organization AI cost.')}</span></div></div></section>
    <section className="agent-editor-section"><div className="agent-editor-heading"><span>04</span><div><h3>{tr('الباقة والتسعير','Plan & pricing')}</h3><p>{tr('هذه البيانات تجارية ولا تظهر لمسؤولي الجهة.','Commercial data is Super Admin only.')}</p></div></div><div className="agent-form-grid three"><label>{tr('اسم الباقة','Plan name')}<input required value={editing.plan_name} onChange={e=>patch({plan_name:e.target.value})}/></label><label>{tr('السعر الشهري','Monthly price')}<input type="number" min="0" step="0.01" value={editing.monthly_price} onChange={e=>patch({monthly_price:Number(e.target.value)})}/></label><label>{tr('العملة','Currency')}<select value={editing.billing_currency} onChange={e=>patch({billing_currency:e.target.value as Agent['billing_currency']})}><option>SAR</option><option>USD</option><option>AED</option><option>EUR</option></select></label><label>{tr('الرسائل المشمولة شهريًا','Included monthly messages')}<input type="number" min="0" value={editing.included_monthly_messages??''} onChange={e=>patch({included_monthly_messages:nullableNumber(e.target.value)})}/></label><label>{tr('التوكنات المشمولة شهريًا','Included monthly tokens')}<input type="number" min="0" value={editing.included_monthly_tokens??''} onChange={e=>patch({included_monthly_tokens:nullableNumber(e.target.value)})}/></label><label>{tr('هامش التسعير %','Pricing markup %')}<input type="number" min="0" step="0.1" value={editing.markup_percent} onChange={e=>patch({markup_percent:Number(e.target.value)})}/></label><label>{tr('سقف تكلفة AI الداخلي بالدولار','Internal AI cost cap (USD)')}<input type="number" min="0" step="0.01" value={editing.monthly_ai_cost_limit_usd??''} onChange={e=>patch({monthly_ai_cost_limit_usd:nullableNumber(e.target.value)})}/><FieldHint>{tr('عند بلوغ السقف يتوقف استهلاك AI ويتحول المسار للدعم البشري.','At the cap, AI consumption stops and routes to human support.')}</FieldHint></label><label className="span-2">{tr('ملاحظات تجارية داخلية','Internal commercial notes')}<textarea rows={3} value={editing.notes??''} onChange={e=>patch({notes:e.target.value})}/></label></div></section>
    {message&&<div className={`notice ${editing.last_test_status==='failed'?'error':''}`} role="status">{message}</div>}<div className="agent-editor-actions"><button type="submit" disabled={busy}>{busy?tr('جارٍ الحفظ…','Saving…'):tr('حفظ الوكيل والباقة','Save agent & plan')}</button><button type="button" className="ghost" onClick={()=>setEditing(null)}>{tr('إلغاء','Cancel')}</button></div>
   </form>}
  </Modal>
 </div>
}
