export type AppRole = 'SUPER_ADMIN' | 'ORGANIZATION_ADMIN' | 'KNOWLEDGE_MANAGER' | 'SUPPORT_AGENT' | 'VIEWER'
export interface Profile { id:string; organization_id:string|null; full_name:string; email:string; role:AppRole; is_active:boolean }
export interface Organization { id:string; code:string; name_ar:string; name_en:string|null; default_language:string; timezone:string; is_active:boolean; created_at:string }
export interface ApiClient { id:string; organization_id:string; name:string; code:string; api_key_prefix:string; is_active:boolean; rate_limit_per_minute:number; capabilities:string[]; allowed_ips:string[]; last_used_at:string|null; created_at:string }
export interface Conversation { id:string; organization_id:string; api_client_id:string|null; customer_id:string; external_conversation_id:string; channel:string; status:string; human_takeover:boolean; ai_enabled:boolean; assigned_user_id:string|null; summary:string|null; closed_at:string|null; last_message_at:string; created_at:string }
export interface Customer { id:string; organization_id:string; external_customer_id:string; display_name:string|null; phone:string|null; email:string|null; language:string|null; last_seen_at:string }
export interface KnowledgeBase { id:string; organization_id:string; name:string; code:string; description:string|null; is_active:boolean; created_at:string }
export interface KnowledgeDocument { id:string; organization_id:string; knowledge_base_id:string; title:string; source_type:string; original_file_name:string|null; storage_path:string|null; source_url:string|null; language:string|null; processing_status:string; processing_error:string|null; is_active:boolean; created_at:string; processed_at:string|null }
export type CustomerIntakeFieldKey='firstName'|'lastName'|'phone'|'email'|'question'
export interface CustomerIntakeFieldRule{visible:boolean;required:boolean}
export type CustomerIntakeFields=Record<CustomerIntakeFieldKey,CustomerIntakeFieldRule>
export interface WebChatWidget { id:string; organization_id:string; api_client_id:string; prompt_profile_id:string|null; knowledge_base_id:string|null; name:string; public_key:string; title_ar:string; title_en:string; welcome_ar:string; welcome_en:string; placeholder_ar:string; placeholder_en:string; suggestions_ar:string[]; suggestions_en:string[]; primary_color:string; position:'bottom_right'|'bottom_left'; allowed_origins:string[]; public_test_enabled:boolean; intake_fields:CustomerIntakeFields; is_active:boolean; created_at:string; updated_at:string }
export interface UsageLog { id:string; organization_id:string; operation:string; provider:string|null; model:string|null; input_tokens:number; output_tokens:number; embedding_tokens:number; estimated_cost:number; created_at:string }
