export type AppRole = 'SUPER_ADMIN' | 'ORGANIZATION_ADMIN' | 'KNOWLEDGE_MANAGER' | 'SUPPORT_AGENT' | 'VIEWER'
export interface Profile { id:string; organization_id:string|null; full_name:string; email:string; role:AppRole; is_active:boolean }
export interface Organization { id:string; code:string; name_ar:string; name_en:string|null; default_language:string; timezone:string; is_active:boolean; created_at:string }
export interface ApiClient { id:string; organization_id:string; name:string; code:string; api_key_prefix:string; is_active:boolean; rate_limit_per_minute:number; capabilities:string[]; allowed_ips:string[]; last_used_at:string|null; created_at:string }
export interface Conversation { id:string; organization_id:string; customer_id:string; external_conversation_id:string; channel:string; status:string; human_takeover:boolean; last_message_at:string; created_at:string }
export interface Customer { id:string; organization_id:string; external_customer_id:string; display_name:string|null; phone:string|null; email:string|null; language:string|null; last_seen_at:string }
export interface KnowledgeBase { id:string; organization_id:string; name:string; code:string; description:string|null; is_active:boolean; created_at:string }
export interface KnowledgeDocument { id:string; organization_id:string; knowledge_base_id:string; title:string; source_type:string; original_file_name:string|null; storage_path:string|null; source_url:string|null; language:string|null; processing_status:string; processing_error:string|null; is_active:boolean; created_at:string; processed_at:string|null }
export interface UsageLog { id:string; organization_id:string; operation:string; provider:string|null; model:string|null; input_tokens:number; output_tokens:number; embedding_tokens:number; estimated_cost:number; created_at:string }
