import { useEffect,useState } from 'react'
import { supabase } from '../../lib/supabase'
import { resourceAdmin } from '../../lib/resourceAdmin'
import { Card, Empty, Modal, PageHeader, PanelHeader, Badge } from '../../components/Ui'
import type { Customer } from '../../types/domain'
import { useI18n, type AppLanguage } from '../../lib/i18n'

export function Customers(){
  const {tr,formatDate,valueLabel}=useI18n();const [rows,setRows]=useState<Customer[]>([]);const [message,setMessage]=useState('');const [editing,setEditing]=useState<Customer|null>(null);const [name,setName]=useState('');const [phone,setPhone]=useState('');const [email,setEmail]=useState('');const [language,setLanguage]=useState<AppLanguage>('ar')
  const load=async()=>{const result=await supabase.from('customers').select('*').order('last_seen_at',{ascending:false}).limit(200);setRows((result.data??[]) as Customer[])}
  useEffect(()=>{void load()},[])
  const openEdit=(row:Customer)=>{setEditing(row);setName(row.display_name??'');setPhone(row.phone??'');setEmail(row.email??'');setLanguage(row.language==='en'?'en':'ar')}
  const save=async(e:React.FormEvent)=>{e.preventDefault();if(!editing)return;try{await resourceAdmin({action:'update_customer',id:editing.id,displayName:name,phone,email,language});setMessage(tr('تم حفظ بيانات العميل.','Customer details saved.'));setEditing(null);await load()}catch(err){setMessage(err instanceof Error?err.message:tr('تعذر تعديل العميل.','Unable to update customer.'))}}
  const remove=async(row:Customer)=>{if(!confirm(tr('حذف هذا العميل؟ سيتم رفض الحذف تلقائيًا إذا كان لديه سجل محادثات.','Delete this customer? Deletion is automatically blocked if conversation history exists.')))return;try{await resourceAdmin({action:'delete_customer',id:row.id});setMessage(tr('تم حذف العميل.','Customer deleted.'));await load()}catch(err){setMessage(err instanceof Error?err.message:tr('تعذر حذف العميل.','Unable to delete customer.'))}}
  return <div className="screen screen-customers"><PageHeader title={tr('العملاء','Customers')} description={tr('تعديل معلومات الاتصال واللغة، مع منع حذف أي عميل لديه سجل محادثات للحفاظ على التاريخ.','Edit contact details and language while preventing deletion of customers that have conversation history.')}/><Card className="table-card data-panel"><PanelHeader title={tr('سجل العملاء','Customer registry')} description={tr('المعرف الخارجي ثابت لأنه رابط التكامل مع النظام المصدر.','The external identifier stays immutable because it is the integration link to the source system.')} meta={<Badge>{rows.length}</Badge>}/>{message&&<div className="inline-feedback" role="status">{message}</div>}{rows.length===0?<Empty>{tr('لا يوجد عملاء.','No customers found.')}</Empty>:<table className="data-table"><thead><tr><th>{tr('المعرف الخارجي','External ID')}</th><th>{tr('الاسم','Name')}</th><th>{tr('الهاتف','Phone')}</th><th>{tr('البريد','Email')}</th><th>{tr('اللغة','Language')}</th><th>{tr('آخر ظهور','Last seen')}</th><th className="actions-cell">{tr('الإجراءات','Actions')}</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><code>{row.external_customer_id}</code></td><td className="cell-primary">{row.display_name??'—'}</td><td dir="ltr">{row.phone??'—'}</td><td dir="ltr">{row.email??'—'}</td><td>{valueLabel(row.language)}</td><td>{formatDate(row.last_seen_at)}</td><td className="actions-cell"><div className="row-actions"><button className="small ghost" onClick={()=>openEdit(row)}>{tr('تعديل','Edit')}</button><button className="small danger-action" onClick={()=>void remove(row)}>{tr('حذف','Delete')}</button></div></td></tr>)}</tbody></table>}</Card><Modal open={Boolean(editing)} onClose={()=>setEditing(null)} title={tr('تعديل العميل','Edit customer')}><form className="modal-grid" onSubmit={save}><label>{tr('الاسم','Name')}<input value={name} onChange={e=>setName(e.target.value)}/></label><label>{tr('اللغة','Language')}<select value={language} onChange={e=>setLanguage(e.target.value as AppLanguage)}><option value="ar">{tr('العربية','Arabic')}</option><option value="en">{tr('الإنجليزية','English')}</option></select></label><label>{tr('الهاتف','Phone')}<input dir="ltr" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>{tr('البريد','Email')}<input type="email" dir="ltr" value={email} onChange={e=>setEmail(e.target.value)}/></label><div className="form-actions span-2"><button>{tr('حفظ التعديلات','Save changes')}</button><button type="button" className="ghost" onClick={()=>setEditing(null)}>{tr('إلغاء','Cancel')}</button></div></form></Modal></div>
}
