import { useEffect,useState } from 'react'
import { supabase } from '../../lib/supabase'
import { adminApi } from '../../lib/adminApi'
import { Card, Empty, PageHeader } from '../../components/Ui'
import type { AppRole,Organization,Profile } from '../../types/domain'
import { useI18n } from '../../lib/i18n'

export function Users({profile}:{profile:Profile}){const {tr,valueLabel}=useI18n();const [users,setUsers]=useState<Profile[]>([]);const [orgs,setOrgs]=useState<Organization[]>([]);const [email,setEmail]=useState('');const [fullName,setFullName]=useState('');const [role,setRole]=useState<AppRole>('ORGANIZATION_ADMIN');const [organizationId,setOrganizationId]=useState(profile.organization_id??'');const [message,setMessage]=useState('')
 const load=async()=>{const [u,o]=await Promise.all([supabase.from('profiles').select('*').order('created_at',{ascending:false}),supabase.from('organizations').select('*').order('name_ar')]);setUsers((u.data??[]) as Profile[]);setOrgs((o.data??[]) as Organization[])};useEffect(()=>{void load()},[])
 const invite=async(e:React.FormEvent)=>{e.preventDefault();setMessage('');try{await adminApi({action:'invite_user',email,fullName,userRole:role,organizationId:role==='SUPER_ADMIN'?null:organizationId});setMessage(tr('تم إرسال الدعوة.','Invitation sent.'));setEmail('');setFullName('');await load()}catch(err){setMessage(err instanceof Error?err.message:tr('تعذر إرسال الدعوة','Unable to send invitation'))}}
 return <><PageHeader title={tr('المستخدمون','Users')} description={tr('إدارة دعوات Supabase Auth والأدوار متعددة الجهات.','Manage Supabase Auth invitations and multi-tenant roles.')}/><Card><form className="grid-form" onSubmit={invite}><input required placeholder={tr('الاسم الكامل','Full name')} value={fullName} onChange={e=>setFullName(e.target.value)}/><input required type="email" placeholder="email@example.com" value={email} onChange={e=>setEmail(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value as AppRole)}>{profile.role==='SUPER_ADMIN'&&<option value="SUPER_ADMIN">{valueLabel('SUPER_ADMIN')}</option>}<option value="ORGANIZATION_ADMIN">{valueLabel('ORGANIZATION_ADMIN')}</option><option value="KNOWLEDGE_MANAGER">{valueLabel('KNOWLEDGE_MANAGER')}</option><option value="SUPPORT_AGENT">{valueLabel('SUPPORT_AGENT')}</option><option value="VIEWER">{valueLabel('VIEWER')}</option></select>{role!=='SUPER_ADMIN'&&<select required value={organizationId} onChange={e=>setOrganizationId(e.target.value)}><option value="">{tr('اختر الجهة','Select organization')}</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name_ar} / {o.name_en}</option>)}</select>}<button>{tr('إرسال دعوة','Send invitation')}</button></form>{message&&<p>{message}</p>}</Card><Card>{users.length===0?<Empty>{tr('لا يوجد مستخدمون.','No users found.')}</Empty>:<table><thead><tr><th>{tr('الاسم','Name')}</th><th>{tr('البريد','Email')}</th><th>{tr('الدور','Role')}</th><th>{tr('الحالة','Status')}</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.full_name}</td><td>{u.email}</td><td>{valueLabel(u.role)}</td><td>{u.is_active?tr('نشط','Active'):tr('متوقف','Inactive')}</td></tr>)}</tbody></table>}</Card></>}
