import { useEffect,useState } from 'react'
import { supabase } from '../../lib/supabase'
import { adminApi } from '../../lib/adminApi'
import { Card, Empty, PageHeader } from '../../components/Ui'
import type { AppRole,Organization,Profile } from '../../types/domain'
export function Users({profile}:{profile:Profile}){const [users,setUsers]=useState<Profile[]>([]);const [orgs,setOrgs]=useState<Organization[]>([]);const [email,setEmail]=useState('');const [fullName,setFullName]=useState('');const [role,setRole]=useState<AppRole>('ORGANIZATION_ADMIN');const [organizationId,setOrganizationId]=useState(profile.organization_id??'');const [message,setMessage]=useState('')
 const load=async()=>{const [u,o]=await Promise.all([supabase.from('profiles').select('*').order('created_at',{ascending:false}),supabase.from('organizations').select('*').order('name_ar')]);setUsers((u.data??[]) as Profile[]);setOrgs((o.data??[]) as Organization[])};useEffect(()=>{void load()},[])
 const invite=async(e:React.FormEvent)=>{e.preventDefault();setMessage('');try{await adminApi({action:'invite_user',email,fullName,userRole:role,organizationId:role==='SUPER_ADMIN'?null:organizationId});setMessage('تم إرسال الدعوة.');setEmail('');setFullName('');await load()}catch(err){setMessage(err instanceof Error?err.message:'تعذر إرسال الدعوة')}}
 return <><PageHeader title="المستخدمون" description="دعوات Supabase Auth مع أدوار متعددة الجهات."/><Card><form className="grid-form" onSubmit={invite}><input required placeholder="الاسم الكامل" value={fullName} onChange={e=>setFullName(e.target.value)}/><input required type="email" placeholder="email@example.com" value={email} onChange={e=>setEmail(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value as AppRole)}>{profile.role==='SUPER_ADMIN'&&<option>SUPER_ADMIN</option>}<option>ORGANIZATION_ADMIN</option><option>KNOWLEDGE_MANAGER</option><option>SUPPORT_AGENT</option><option>VIEWER</option></select>{role!=='SUPER_ADMIN'&&<select required value={organizationId} onChange={e=>setOrganizationId(e.target.value)}><option value="">اختر الجهة</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name_ar}</option>)}</select>}<button>إرسال دعوة</button></form>{message&&<p>{message}</p>}</Card><Card>{users.length===0?<Empty>لا يوجد مستخدمون.</Empty>:<table><thead><tr><th>الاسم</th><th>البريد</th><th>الدور</th><th>الحالة</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.full_name}</td><td>{u.email}</td><td>{u.role}</td><td>{u.is_active?'نشط':'متوقف'}</td></tr>)}</tbody></table>}</Card></>}
