import { useEffect,useState } from 'react'
import { supabase } from '../../lib/supabase'
import { adminApi } from '../../lib/adminApi'
import { Badge, Card, Empty, FieldHint, Modal, PageHeader, PanelHeader } from '../../components/Ui'
import type { Organization,Profile } from '../../types/domain'
import { useI18n, type AppLanguage } from '../../lib/i18n'

export function Organizations({profile}:{profile:Profile}){
  const {tr,valueLabel}=useI18n()
  const [rows,setRows]=useState<Organization[]>([])
  const [nameAr,setNameAr]=useState('');const [nameEn,setNameEn]=useState('');const [code,setCode]=useState('');const [defaultLanguage,setDefaultLanguage]=useState<AppLanguage>('ar')
  const [error,setError]=useState('');const [message,setMessage]=useState('');const [editing,setEditing]=useState<Organization|null>(null)
  const [editNameAr,setEditNameAr]=useState('');const [editNameEn,setEditNameEn]=useState('');const [editLanguage,setEditLanguage]=useState<AppLanguage>('ar');const [editTimezone,setEditTimezone]=useState('Asia/Riyadh')
  const load=async()=>{const {data,error}=await supabase.from('organizations').select('*').order('created_at',{ascending:false});if(error)setError(error.message);else setRows((data??[]) as Organization[])}
  useEffect(()=>{void load()},[])
  const create=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await adminApi({action:'create_organization',nameAr:nameAr.trim(),nameEn:nameEn.trim(),code,defaultLanguage});setNameAr('');setNameEn('');setCode('');setMessage(tr('تم إنشاء الجهة.','Organization created.'));await load()}catch(cause){setError(cause instanceof Error?cause.message:tr('تعذر إنشاء الجهة.','Unable to create organization.'))}}
  const openEdit=(row:Organization)=>{setEditing(row);setEditNameAr(row.name_ar);setEditNameEn(row.name_en??'');setEditLanguage(row.default_language==='en'?'en':'ar');setEditTimezone(row.timezone||'Asia/Riyadh')}
  const save=async(e:React.FormEvent)=>{e.preventDefault();if(!editing)return;const {error}=await supabase.from('organizations').update({name_ar:editNameAr.trim(),name_en:editNameEn.trim()||null,default_language:editLanguage,timezone:editTimezone.trim()||'Asia/Riyadh'}).eq('id',editing.id);setMessage(error?.message??tr('تم حفظ تعديلات الجهة.','Organization changes saved.'));if(!error){setEditing(null);await load()}}
  const toggle=async(row:Organization)=>{if(row.is_active&&!confirm(tr('تعطيل الجهة سيوقف استخدام إعداداتها ومفاتيحها في التشغيل. متابعة؟','Disabling the organization stops its settings and keys from normal operation. Continue?')))return;const {error}=await supabase.from('organizations').update({is_active:!row.is_active}).eq('id',row.id);setMessage(error?.message??tr(row.is_active?'تم تعطيل الجهة.':'تم تفعيل الجهة.',row.is_active?'Organization disabled.':'Organization enabled.'));if(!error)await load()}
  const remove=async(row:Organization)=>{if(!confirm(tr('الحذف النهائي مسموح فقط للجهة الفارغة. هل تريد المحاولة؟','Permanent deletion is only allowed for an empty organization. Try deleting it?')))return;const checks=await Promise.all(['profiles','api_clients','knowledge_bases','customers','conversations'].map(table=>supabase.from(table).select('id',{count:'exact',head:true}).eq('organization_id',row.id)));if(checks.some(result=>(result.count??0)>0)){setMessage(tr('لا يمكن حذف جهة تحتوي على بيانات. عطّلها بدلًا من ذلك أو احذف بياناتها التابعة أولًا.','An organization with dependent data cannot be deleted. Disable it instead or remove dependent data first.'));return}const {error}=await supabase.from('organizations').delete().eq('id',row.id);setMessage(error?.message??tr('تم حذف الجهة.','Organization deleted.'));if(!error)await load()}

  return <div className="screen screen-organizations">
    <PageHeader title={tr('الجهات','Organizations')} description={tr('أنشئ الجهات وأدر بياناتها وحالتها مع منع الحذف غير الآمن للجهات التي تحتوي على بيانات.','Create organizations and manage their details and status while preventing unsafe deletion of organizations that still contain data.')}/>
    <div className={profile.role==='SUPER_ADMIN'?'admin-split':'single-panel'}>
      {profile.role==='SUPER_ADMIN'&&<Card className="form-panel"><PanelHeader title={tr('إنشاء جهة جديدة','Create a new organization')} description={tr('عرّف الاسم والكود واللغة الافتراضية قبل ربط الأنظمة الخارجية.','Define the name, code, and default language before connecting external systems.')} meta={<span className="panel-index">01</span>}/><form className="grid-form compact-form" onSubmit={create}><label>{tr('اسم الجهة بالعربية','Organization name in Arabic')}<input required value={nameAr} onChange={e=>setNameAr(e.target.value)}/></label><label>{tr('اسم الجهة بالإنجليزية','Organization name in English')}<input required value={nameEn} onChange={e=>setNameEn(e.target.value)}/></label><label>{tr('كود الجهة','Organization code')}<input required dir="ltr" value={code} onChange={e=>setCode(e.target.value)} placeholder="WAHA_SCHOOLS"/><FieldHint>{tr('معرف تقني ثابت بدون مسافات. لا نسمح بتعديله لاحقًا لتجنب كسر التكاملات.','A stable technical identifier without spaces. It is intentionally immutable later to avoid breaking integrations.')}</FieldHint></label><label>{tr('اللغة الافتراضية','Default language')}<select value={defaultLanguage} onChange={e=>setDefaultLanguage(e.target.value as AppLanguage)}><option value="ar">{tr('العربية','Arabic')}</option><option value="en">{tr('الإنجليزية','English')}</option></select></label><div className="form-submit-row"><button>{tr('إنشاء الجهة','Create organization')}</button></div></form>{error&&<div className="notice error" role="alert">{error}</div>}{message&&<div className="inline-feedback" role="status">{message}</div>}</Card>}
      <Card className="table-card data-panel"><PanelHeader title={tr('الجهات المسجلة','Registered organizations')} description={tr('يمكن تعديل الاسم واللغة والمنطقة الزمنية، أو تعطيل الجهة، أو حذفها فقط إذا كانت فارغة.','Edit names, language, and timezone; disable an organization; or delete it only when it is empty.')} meta={<Badge>{rows.length}</Badge>}/>{rows.length===0?<Empty>{tr('لا توجد جهات بعد.','No organizations yet.')}</Empty>:<table className="data-table"><thead><tr><th>{tr('الاسم','Name')}</th><th>{tr('الكود','Code')}</th><th>{tr('اللغة','Language')}</th><th>{tr('الحالة','Status')}</th><th className="actions-cell">{tr('الإجراءات','Actions')}</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className={row.is_active?'':'soft-disabled'}><td className="cell-primary"><div>{row.name_ar}</div><small>{row.name_en??'—'}</small></td><td><code>{row.code}</code></td><td>{valueLabel(row.default_language)}</td><td><Badge tone={row.is_active?'good':'bad'}>{row.is_active?tr('نشطة','Active'):tr('متوقفة','Inactive')}</Badge></td><td className="actions-cell"><div className="row-actions"><button className="small ghost" onClick={()=>openEdit(row)}>{tr('تعديل','Edit')}</button><button className={`small ${row.is_active?'warning-action':'success-action'}`} onClick={()=>void toggle(row)}>{row.is_active?tr('تعطيل','Disable'):tr('تفعيل','Enable')}</button><button className="small danger-action" onClick={()=>void remove(row)}>{tr('حذف','Delete')}</button></div></td></tr>)}</tbody></table>}</Card>
    </div>
    <Modal open={Boolean(editing)} onClose={()=>setEditing(null)} title={tr('تعديل الجهة','Edit organization')}><form className="modal-grid" onSubmit={save}><label>{tr('الاسم العربي','Arabic name')}<input required value={editNameAr} onChange={e=>setEditNameAr(e.target.value)}/></label><label>{tr('الاسم الإنجليزي','English name')}<input value={editNameEn} onChange={e=>setEditNameEn(e.target.value)}/></label><label>{tr('اللغة الافتراضية','Default language')}<select value={editLanguage} onChange={e=>setEditLanguage(e.target.value as AppLanguage)}><option value="ar">{tr('العربية','Arabic')}</option><option value="en">{tr('الإنجليزية','English')}</option></select></label><label>{tr('المنطقة الزمنية','Timezone')}<input dir="ltr" value={editTimezone} onChange={e=>setEditTimezone(e.target.value)} placeholder="Asia/Riyadh"/></label><div className="form-actions span-2"><button>{tr('حفظ التعديلات','Save changes')}</button><button type="button" className="ghost" onClick={()=>setEditing(null)}>{tr('إلغاء','Cancel')}</button></div></form></Modal>
  </div>
}
