import { useEffect,useMemo,useState } from 'react'
import { supabase } from '../../lib/supabase'
import { resourceAdmin } from '../../lib/resourceAdmin'
import { Badge, Card, Empty, PageHeader, PanelHeader } from '../../components/Ui'
import { useI18n } from '../../lib/i18n'

interface Row{id:string;conversation_id:string;reason:string;requested_by:string;status:string;requested_at:string;assigned_user_id:string|null;notes:string|null}
const conversationTargetKey='central-ai:selected-conversation'

export function Handoff(){
  const {tr,formatDate,valueLabel}=useI18n();const [rows,setRows]=useState<Row[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState('');const [filter,setFilter]=useState<'all'|'waiting'|'assigned'>('all')
  const load=async()=>{const result=await supabase.from('handoff_requests').select('id,conversation_id,reason,requested_by,status,requested_at,assigned_user_id,notes').in('status',['waiting','assigned']).order('requested_at');setRows((result.data??[]) as Row[])}
  useEffect(()=>{void load()},[])
  const visibleRows=useMemo(()=>filter==='all'?rows:rows.filter(row=>row.status===filter),[rows,filter])
  const run=async(row:Row,action:'claim_handoff'|'resolve_handoff'|'cancel_handoff',success:string)=>{if(busy)return;setBusy(row.id);setMessage('');try{await resourceAdmin({action,id:row.id});setMessage(success);await load()}catch(err){setMessage(valueLabel(err instanceof Error?err.message:tr('تعذر تنفيذ العملية.','Unable to complete the operation.')))}finally{setBusy('')}}
  const claim=async(row:Row)=>run(row,'claim_handoff',tr('تم استلام المحادثة وتفعيل التحكم البشري.','Conversation claimed and human control enabled.'))
  const resolve=async(row:Row)=>run(row,'resolve_handoff',tr('تم حل التحويل واستئناف الذكاء الاصطناعي.','Handoff resolved and AI resumed.'))
  const cancel=async(row:Row)=>{if(!confirm(tr('إلغاء طلب التحويل وإعادة المحادثة للذكاء الاصطناعي؟','Cancel this handoff and return the conversation to AI?')))return;await run(row,'cancel_handoff',tr('تم إلغاء التحويل واستئناف AI.','Handoff cancelled and AI resumed.'))}
  const openConversation=(row:Row)=>{sessionStorage.setItem(conversationTargetKey,row.conversation_id);location.hash='conversations'}
  return <div className="screen screen-handoff"><PageHeader title={tr('التحويل البشري','Human Handoff')} description={tr('قائمة عمل فعلية لخدمة العملاء: افتح المحادثة، استلمها، حل التحويل أو ألغِه مع إبقاء سجل التدقيق محفوظًا.','An actionable customer service queue: open the conversation, claim it, resolve the handoff, or cancel it while preserving audit history.')}/>{message&&<div className="inline-feedback" role="status">{message}</div>}<Card className="data-panel"><PanelHeader title={tr('طلبات التحويل المفتوحة','Open handoff requests')} description={tr('طلبات الانتظار والإسناد الحالية فقط؛ السجل التاريخي يبقى محفوظًا في قاعدة البيانات والتدقيق.','Only active waiting and assigned requests are shown here; historical records remain preserved in the database and audit log.')} meta={<Badge>{visibleRows.length}</Badge>}/><div className="handoff-filter-tabs"><button className={filter==='all'?'selected ghost':'ghost'} onClick={()=>setFilter('all')}>{tr('الكل','All')} <span>{rows.length}</span></button><button className={filter==='waiting'?'selected ghost':'ghost'} onClick={()=>setFilter('waiting')}>{tr('بانتظار الاستلام','Waiting')} <span>{rows.filter(row=>row.status==='waiting').length}</span></button><button className={filter==='assigned'?'selected ghost':'ghost'} onClick={()=>setFilter('assigned')}>{tr('تم استلامها','Assigned')} <span>{rows.filter(row=>row.status==='assigned').length}</span></button></div>{visibleRows.length===0?<Empty>{tr('لا توجد محادثات في هذه الفئة.','No conversations in this queue.')}</Empty>:<div className="handoff-cards">{visibleRows.map(row=><article className="handoff-card" key={row.id}><div className="handoff-card-main"><div className="handoff-card-title"><div><span>{tr('محادثة','Conversation')}</span><code>{row.conversation_id.slice(0,8)}</code></div><Badge tone={row.status==='assigned'?'good':'warn'}>{valueLabel(row.status)}</Badge></div><div className="handoff-card-meta"><span><small>{tr('سبب التحويل','Reason')}</small><strong>{valueLabel(row.reason)}</strong></span><span><small>{tr('منذ','Since')}</small><strong>{formatDate(row.requested_at)}</strong></span>{row.notes&&<span className="handoff-note"><small>{tr('ملاحظة','Note')}</small><strong>{row.notes}</strong></span>}</div></div><div className="handoff-card-actions"><button className="small ghost" disabled={Boolean(busy)} onClick={()=>openConversation(row)}>{tr('فتح المحادثة','Open conversation')}</button>{row.status==='waiting'&&<button className="small" disabled={Boolean(busy)} onClick={()=>void claim(row)}>{tr('استلام','Claim')}</button>}<button className="small success-action" disabled={Boolean(busy)} onClick={()=>void resolve(row)}>{tr('حل واستئناف AI','Resolve & resume AI')}</button><button className="small danger-action" disabled={Boolean(busy)} onClick={()=>void cancel(row)}>{tr('إلغاء التحويل','Cancel handoff')}</button></div></article>)}</div>}</Card></div>
}
